name: Create NX Service

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Name of the new service'
        required: true
        type: string
      task_number:
        description: 'Task/ticket number (e.g., TASK-123)'
        required: true
        type: string

jobs:
  create-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate service
        run: npx nx g @nx/react:library libs/${{ github.event.inputs.service_name }} --unitTestRunner=vitest --bundler=none

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: '${{ github.event.inputs.task_number }}: Create service ${{ github.event.inputs.service_name }}'
          branch: 'feature/${{ github.event.inputs.task_number }}-create-${{ github.event.inputs.service_name }}'
          commit-message: 'feat: create service ${{ github.event.inputs.service_name }}'
          body: |
            Creates new service ${{ github.event.inputs.service_name }}

            Task: ${{ github.event.inputs.task_number }}
