name: Create NX lib

on:
  workflow_dispatch:
    inputs:
      lib_name:
        description: 'Name of the new lib'
        required: true
        type: string
      task_number:
        description: 'Task/ticket number'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  create-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Create and switch to new branch
        run: |
          git config --global user.name "${{ vars.AUTOMATON_GIT_NAME }}"
          git config --global user.email "${{ vars.AUTOMATON_GIT_EMAIL }}"
          git checkout -b ${{ github.event.inputs.task_number }}-create-${{ github.event.inputs.lib_name }}

      - name: Generate lib
        run: npx nx g @nx/react:library libs/${{ github.event.inputs.lib_name }} --unitTestRunner=vitest --bundler=none

      - name: Commit changes
        run: |
          git add .
          git commit -m "${{ github.event.inputs.task_number }} Create lib ${{ github.event.inputs.lib_name }}"
          git push origin ${{ github.event.inputs.task_number }}-create-${{ github.event.inputs.lib_name }}

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --title "${{ github.event.inputs.task_number }} Create lib ${{ github.event.inputs.lib_name }}" \
            --base main \
            --head ${{ github.event.inputs.task_number }}-create-${{ github.event.inputs.lib_name }} \
            --label "automated-pr"
