name: Create NX lib

on:
  workflow_dispatch:
    inputs:
      lib_name:
        description: 'Name of the new lib'
        required: true
        type: string
      task_number:
        description: 'Task/ticket number'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  create-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Setup Git and Create Branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Clean fetch and branch creation
          git fetch origin
          git checkout -B main origin/main

          # Delete branch locally and remotely if it exists
          git branch -D ${{ github.event.inputs.task_number }}-create-${{ github.event.inputs.lib_name }} || true
          git push origin --delete ${{ github.event.inputs.task_number }}-create-${{ github.event.inputs.lib_name }} || true

          # Create fresh branch
          git checkout -b ${{ github.event.inputs.task_number }}-create-${{ github.event.inputs.lib_name }}

      - name: Create Empty PR First
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Create an empty commit to initialize the branch
          git commit --allow-empty -m "Initialize ${{ github.event.inputs.task_number }}-create-${{ github.event.inputs.lib_name }}"
          git push -f origin ${{ github.event.inputs.task_number }}-create-${{ github.event.inputs.lib_name }}

          # Create PR immediately after branch creation
          gh pr create \
            --title "${{ github.event.inputs.task_number }} Create lib ${{ github.event.inputs.lib_name }}" \
            --body "This PR creates a new library: ${{ github.event.inputs.lib_name }}" \
            --base main \
            --head "${{ github.event.inputs.task_number }}-create-${{ github.event.inputs.lib_name }}"

      - name: Generate lib
        run: npx nx g @nx/react:library libs/${{ github.event.inputs.lib_name }} --unitTestRunner=vitest --bundler=none

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "${{ github.event.inputs.task_number }} Create lib ${{ github.event.inputs.lib_name }}"
          git push origin ${{ github.event.inputs.task_number }}-create-${{ github.event.inputs.lib_name }}
