name: Create NX lib

on:
  workflow_dispatch:
    inputs:
      lib_name:
        description: 'Name of the new lib'
        required: true
        type: string
      task_number:
        description: 'Task/ticket number'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  create-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Generate lib
        run: npx nx g @nx/react:library libs/${{ github.event.inputs.lib_name }} --unitTestRunner=vitest --bundler=none

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: '${{ github.event.inputs.task_number }} Create lib ${{ github.event.inputs.lib_name }}'
          branch: '${{ github.event.inputs.task_number }}-create-${{ github.event.inputs.lib_name }}'
          commit-message: '${{ github.event.inputs.task_number }} Create lib ${{ github.event.inputs.lib_name }}'
